# Generated by Django 2.1.7 on 2020-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200724_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summery',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
