# Generated by Django 2.1.7 on 2020-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200724_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
